require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
require_relative '../node_modules/react-native-unimodules/cocoapods.rb'

platform :ios, '12.0'

target 'WBW' do 
  use_unimodules!
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => false
  )
  $RNFirebaseAsStaticFramework = true

  pod 'GoogleUtilities', modular_headers: true
  pod 'FirebaseCore', modular_headers: true

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'


  
end
